// examples/kit-nextjs-skate-park/src/components/image/Image.tsx
import {
  Field,
  ImageField,
  NextImage as ContentSdkImage,
  Link as ContentSdkLink,
  LinkField,
  Text,
} from "@sitecore-content-sdk/nextjs";
import React from "react";
import { ComponentProps } from "lib/component-props";

interface ImageFields {
  Image: ImageField;
  ImageCaption: Field<string>;
  TargetUrl: LinkField;
}

interface ImageProps extends ComponentProps {
  fields: ImageFields;
}

const ImageWrapper: React.FC<{
  className: string;
  id?: string;
  children: React.ReactNode;
}> = ({ className, id, children }) => (
  <div className={className.trim()} id={id}>
    <div className="component-content">{children}</div>
  </div>
);

const ImageDefault: React.FC<ImageProps> = ({ params }) => (
  <ImageWrapper className={`component image ${params.styles}`}>
    <span className="is-empty-hint">Image</span>
  </ImageWrapper>
);

export const Banner: React.FC<ImageProps> = ({ params, fields }) => {
  const { styles, RenderingIdentifier: id } = params;
  const imageField = fields.Image && {
    ...fields.Image,
    value: {
      ...fields.Image.value,
      style: { objectFit: "cover", width: "100%", height: "100%" },
    },
  };

  return (
    <div className={`component hero-banner ${styles}`.trim()} id={id}>
      <div className="component-content sc-sxa-image-hero-banner">
        <ContentSdkImage
          field={imageField}
          loading="eager"
          fetchPriority="high"
        />
      </div>
    </div>
  );
};

export const Default: React.FC<ImageProps> = (props) => {
  const { fields, params, page } = props;
  const { styles, RenderingIdentifier: id } = params;

  if (!fields) {
    return <ImageDefault {...props} />;
  }

  const Image = () => (
    <ContentSdkImage
      field={fields.Image}
      unoptimized={true}
      imageParams={{ mw: 100, mh: 50 }}
      width={100}
      height={50}
    />
  );
  const shouldWrapWithLink =
    !page.mode.isEditing && fields.TargetUrl?.value?.href;

  return (
    <ImageWrapper className={`component image ${styles}`} id={id}>
      {shouldWrapWithLink ? (
        <ContentSdkLink field={fields.TargetUrl}>
          <Image />
        </ContentSdkLink>
      ) : (
        <Image />
      )}
      <Text
        tag="span"
        className="image-caption field-imagecaption"
        field={fields.ImageCaption}
      />
    </ImageWrapper>
  );
};

// examples/angular/src/app/components/image.component.ts
import { Component, computed, inject } from '@angular/core';
import {
  Field,
  ImageField,
  LinkField,
  ScImageDirective,
  ScLinkDirective,
  ScTextDirective,
  SitecoreContextService,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

const DEFAULT_SIZES =
  '(max-width: 640px) 100vw, (max-width: 768px) 100vw, (max-width: 1024px) 90vw, 1200px';

const BANNER_SIZES =
  '(max-width: 640px) 100vw, (max-width: 768px) 768px, (max-width: 1024px) 1024px, (max-width: 1440px) 1280px, 1920px';

interface ImageDefaultFields {
  Image?: ImageField;
  ImageCaption?: Field<string>;
  TargetUrl?: LinkField;
}

interface ImageBannerFields {
  Image?: ImageField;
}

@Component({
  selector: 'app-image-default',
  imports: [ScImageDirective, ScLinkDirective, ScTextDirective],
  host: {
    '[attr.class]': "('component image ' + styles().trim())",
    '[attr.id]': 'renderingId()',
  },
  template: `
    <div class="component-content">
      @if (wrapWithLink()) {
      <a *scLink="targetUrlField()!">
        <img *scImage="imageField()" [attr.sizes]="defaultSizes" [attr.alt]="imageAlt()" />
      </a>
      } @else {
      <img *scImage="imageField()" [attr.sizes]="defaultSizes" [attr.alt]="imageAlt()" />
      }
      <span class="image-caption field-imagecaption" *scText="captionField()"></span>
    </div>
  `,
})
class ImageDefaultComponent extends SxaComponent {
  readonly defaultSizes = DEFAULT_SIZES;

  private readonly context = inject(SitecoreContextService);

  readonly imageField = computed(() => (this.fields() as ImageDefaultFields)?.Image);
  readonly captionField = computed(() => (this.fields() as ImageDefaultFields)?.ImageCaption);
  readonly targetUrlField = computed(() => (this.fields() as ImageDefaultFields)?.TargetUrl);

  readonly wrapWithLink = computed(() => {
    if (this.context.isEditing()) return false;
    const href = this.targetUrlField()?.value?.href;
    return !!href?.trim();
  });

  readonly imageAlt = computed(() => {
    const alt = this.imageField()?.value?.alt;
    return typeof alt === 'string' ? alt : '';
  });
}

@Component({
  selector: 'app-image-banner',
  imports: [ScImageDirective],
  host: {
    '[attr.class]': "('component hero-banner ' + styles().trim())",
    '[attr.id]': 'renderingId()',
  },
  template: `
    <div class="component-content sc-sxa-image-hero-banner">
      <img
        *scImage="bannerImageField()"
        [attr.sizes]="bannerSizes"
        loading="eager"
        fetchpriority="high"
        [attr.alt]="bannerAlt()"
        [style.object-fit]="'cover'"
        [style.width]="'100%'"
        [style.height]="'100%'"
      />
    </div>
  `,
})
class ImageBannerComponent extends SxaComponent {
  readonly bannerSizes = BANNER_SIZES;

  readonly bannerImageField = computed(() => {
    const sourceImage = (this.fields() as ImageBannerFields)?.Image;
    if (!sourceImage?.value) return sourceImage;
    return {
      ...sourceImage,
      value: {
        ...sourceImage.value,
        style: { objectFit: 'cover', width: '100%', height: '100%' },
      },
    } as ImageField;
  });

  readonly bannerAlt = computed(() => {
    const alt = (this.fields() as ImageBannerFields)?.Image?.value?.alt;
    return typeof alt === 'string' ? alt : 'Hero banner';
  });
}

export { ImageDefaultComponent as Default, ImageBannerComponent as Banner };
